# Generated by Django 3.1.3 on 2020-11-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AddField(
            model_name='user',
            name='plans',
            field=models.ManyToManyField(blank=True, to='img_upload.Plan', verbose_name='Plany'),
        ),
    ]
