# Generated by Django 3.1.3 on 2020-11-11 08:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nazwa planu')),
                ('width', models.PositiveSmallIntegerField(null=True, verbose_name='Szerokość')),
                ('height', models.PositiveSmallIntegerField(null=True, verbose_name='Wysokość')),
                ('original_size', models.BooleanField(default=False, verbose_name='Oryginalne zdjęcie')),
                ('exp_date', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(30)], verbose_name='Wygaśnięcie')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plany',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Zdjęcie')),
                ('file', models.ImageField(default='main_imgs/none.jpg', upload_to='main_imgs/', verbose_name='Plik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stworzone')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Twórca')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
