# Generated by Django 3.1.3 on 2020-11-08 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('img_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nazwa planu')),
                ('width', models.PositiveSmallIntegerField(null=True, verbose_name='Szerokość')),
                ('height', models.PositiveSmallIntegerField(null=True, verbose_name='Wysokość')),
                ('original_size', models.BooleanField(default=False, verbose_name='Oryginalne zdjęcie')),
                ('exp_date', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(30)], verbose_name='Wygaśnięcie')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plany',
            },
        ),
    ]
