# Generated by Django 3.1.3 on 2020-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(null=True, verbose_name='Szerokość')),
                ('height', models.PositiveSmallIntegerField(null=True, verbose_name='Wysokość')),
            ],
            options={
                'verbose_name': 'Rozmiar',
                'verbose_name_plural': 'Rozmiar',
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='height',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='width',
        ),
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.ManyToManyField(blank=True, to='img_upload.Size', verbose_name='Rozmiar'),
        ),
    ]
