# Generated by Django 3.1.3 on 2020-11-11 19:00

from django.db import migrations


def create_plans(apps, schema_editor):
    from django.utils.translation import gettext as _
    from img_upload.models import Size, Plan
    from users.models import User
    BASIC = 'basic'
    PREMIUM = 'premium'
    ENTERPRISE = 'enterprise'
    PLAN_NAME = {
        BASIC: _('basic'),
        PREMIUM: _('premium'),
        ENTERPRISE: _('enterprise')
    }
    try:
        User.objects.create_superuser(username='admin', password='admin')
        first_size = Size.objects.create(width=200, height=200)
        second_size = Size.objects.create(width=400, height=400)

        bas = Plan.objects.create(name=BASIC, original_size=False, exp_date=False)
        bas.size.add(first_size)

        prem = Plan.objects.create(name=PREMIUM, original_size=True, exp_date=False)
        prem.size.add(first_size, second_size)

        ent = Plan.objects.create(name=ENTERPRISE, original_size=True, exp_date=True)
        ent.size.add(first_size, second_size)
    except:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('img_upload', '0003_auto_20201111_1032'),
    ]

    operations = [
        migrations.RunPython(create_plans)
    ]
